from .GraduateList import GraduateList
from .GraduateDossier import GraduateDossier
from .GraduateFile import GraduateFile
from .SettingsSignature import SettingsSignature
from .InaugurationGroup import InaugurationGroup
from .ARPGroup import ARPGroup
from .Rubricator import Rubricator
from .AEPGeneration import AEPGeneration
from .GraduateLiberation import GraduateLiberation
