export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_DATA_START = "GET_DATA_START";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";
export const CREATE_DATA_SUCCESS = "CREATE_DATA_SUCCESS";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const GET_DATA_FAIL = "GET_DATA_FAIL";
export const RESET_DATA = "RESET_DATA";

export const TRANSACTION_START = "TRANSACTION_START";
export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
export const TRANSACTION_FAIL = "TRANSACTION_FAIL";

export const SERVERDATA_START = "SERVERDATA_START";
export const SERVERDATA_SUCCESS = "SERVERDATA_SUCCESS";
export const SERVERDATA_FAIL = "SERVERDATA_FAIL";
export const SERVERDATA_RESET = "SERVERDATA_RESET";

export const ADMIN_TRANSACTION_START = "ADMIN_TRANSACTION_START";
export const ADMIN_TRANSACTION_SUCCESS = "ADMIN_TRANSACTION_SUCCESS";
export const ADMIN_TRANSACTION_FAIL = "ADMIN_TRANSACTION_FAIL";
export const ADMIN_TRANSACTION_RESET = "ADMIN_TRANSACTION_RESET";

export const ACTION_START = "ACTION_START";
export const ACTION_SUCCESS = "ACTION_SUCCESS";
export const ACTION_FAIL = "ACTION_FAIL";
