# Generated by Django 3.2.8 on 2022-01-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('no_graduate', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='graduateprofile',
            name='i_date',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='i_date', to='users.dategroup'),
        ),
    ]
