# Generated by Django 3.2.8 on 2022-01-19 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_arpdata_arpgroup_arpprocessperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARPStaff',
            fields=[
                ('id_card', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=254)),
                ('profession', models.CharField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='arpdata',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president', to='users.arpstaff'),
        ),
        migrations.AlterField(
            model_name='arpdata',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary', to='users.arpstaff'),
        ),
        migrations.AlterField(
            model_name='arpdata',
            name='vocal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocal', to='users.arpstaff'),
        ),
        migrations.DeleteModel(
            name='ARPProcessPerson',
        ),
    ]
