# Generated by Django 3.2.6 on 2021-08-20 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210613_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='type_user',
            new_name='user_type',
        ),
    ]
