# Generated by Django 3.2.8 on 2022-01-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_arpdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARPData',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('record_page', models.IntegerField(blank=True)),
                ('institute', models.CharField(blank=True, max_length=254)),
                ('project_name', models.CharField(blank=True, max_length=254)),
                ('int_assessor_name', models.CharField(blank=True, max_length=254)),
                ('arp_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arp_group', to='users.arpgroup')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduate', to='users.graduateprofile')),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president', to='users.arpstaff')),
                ('secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary', to='users.arpstaff')),
                ('vocal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocal', to='users.arpstaff')),
            ],
        ),
    ]
