# Generated by Django 3.2.8 on 2022-01-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_arpdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='arpgroup',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arpgroup',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
