# Generated by Django 3.2.8 on 2022-01-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220122_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='dategroup',
            name='arp_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dategroup',
            name='arp_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dategroup',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
