# Generated by Django 3.2.8 on 2022-01-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220122_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arpdata',
            name='arp_group',
        ),
    ]
