# Generated by Django 3.2.8 on 2022-01-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_arpdata_record_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arpdata',
            name='graduate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduate', to='users.graduateprofile'),
        ),
    ]
