# Generated by Django 3.2.8 on 2022-02-04 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_arpdata_graduate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateDocuments',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('keyName', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=120)),
                ('fileName', models.CharField(max_length=254)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(max_length=254)),
                ('lastModifiedDate', models.DateTimeField()),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_id', to='users.graduateprofile')),
            ],
        ),
    ]
