# Generated by Django 3.2.8 on 2022-02-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_graduatedocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateprocedurehistory',
            name='last_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
