# Generated by Django 3.2.8 on 2022-02-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220210_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateprofile',
            name='cellphone',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
    ]
