# Generated by Django 3.2.8 on 2022-01-21 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_type', models.CharField(blank=True, max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ARPGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_date', models.DateTimeField()),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ARPStaff',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_card', models.IntegerField(unique=True)),
                ('full_name', models.CharField(blank=True, max_length=254)),
                ('profession', models.CharField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DateGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('no_graduate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastModifiedDate', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=256)),
                ('upload_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GraduateProfile',
            fields=[
                ('enrollment', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('career', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('titulation_type', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('accurate_docs', models.BooleanField(default=False)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
                ('i_date', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='i_date', to='users.dategroup')),
            ],
        ),
        migrations.CreateModel(
            name='GraduateProcedureHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(editable=False)),
                ('information', models.CharField(max_length=254)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_id', to='users.graduateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GraduateNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(editable=False)),
                ('sender', models.CharField(max_length=120)),
                ('type', models.CharField(default='Default', max_length=30)),
                ('message', models.CharField(max_length=254)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_id', to='users.graduateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ARPData',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('record_page', models.IntegerField(blank=True)),
                ('institute', models.CharField(blank=True, max_length=254)),
                ('project_name', models.CharField(blank=True, max_length=254)),
                ('int_assessor_name', models.CharField(blank=True, max_length=254)),
                ('arp_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arp_group', to='users.arpgroup')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduate', to='users.graduateprofile')),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president', to='users.arpstaff')),
                ('secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary', to='users.arpstaff')),
                ('vocal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocal', to='users.arpstaff')),
            ],
        ),
    ]
