# Generated by Django 3.2.8 on 2022-01-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_arpdata_arp_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arpdata',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president_id', to='users.arpstaff'),
        ),
        migrations.AlterField(
            model_name='arpdata',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_id', to='users.arpstaff'),
        ),
        migrations.AlterField(
            model_name='arpdata',
            name='vocal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocal_id', to='users.arpstaff'),
        ),
    ]
