# Generated by Django 3.2.8 on 2022-01-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220123_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arpdata',
            name='record_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
