# Generated by Django 3.2.8 on 2022-02-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_graduateprocedurehistory_last_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='arpdata',
            name='record_book',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graduateprofile',
            name='cellphone',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
