// AUTH
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// USERS
export const WRITE_USER = "WRITE_USER";

// PAGES
export const WRITE_ACTUAL_PAGE = "WRITE_ACTUAL_PAGE";

// FILES
export const GET_FILES = "GET_FILES";
export const UPLOAD_FILE = "UPLOAD_FILE";

// PROCESS TITULATION
export const SET_PROCESS_TITULATION = "SET_PROCESS_TITULATION";