# Generated by Django 3.2.6 on 2021-08-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsDetails',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('keyName', models.CharField(blank=True, max_length=5)),
                ('fullName', models.CharField(max_length=130)),
                ('description', models.CharField(max_length=252)),
                ('required', models.BooleanField(default=True)),
                ('clasification', models.IntegerField()),
            ],
        ),
    ]
