# Generated by Django 3.2.6 on 2021-09-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsdetails',
            name='keyName',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
