const columns = () => {
  return [
    {
      title: "Libro",
      dataIndex: "record_book",
      width: 70,
      fixed: "left",
      editable: true,
      inputType: "number",
    },
    {
      title: "Foja",
      dataIndex: "record_page",
      width: 70,
      fixed: "left",
      editable: true,
      inputType: "number",
    },
    {
      title: "No. Control",
      dataIndex: "enrollment",
      width: 120,
      fixed: "left",
      editable: true,
      inputType: "number",
    },
    {
      title: "Nombre(s)",
      dataIndex: "first_name",
      width: 200,
      editable: true,
      inputType: "text",
    },
    {
      title: "Apellido(s)",
      dataIndex: "last_name",
      width: 200,
      editable: true,
      inputType: "text",
    },
    {
      title: "Correo",
      dataIndex: "email",
      width: 200,
      editable: false,
      inputType: "text",
    },
    {
      title: "No. Celular",
      dataIndex: "cellphone",
      width: 200,
      editable: true,
      inputType: "number",
    },
    {
      title: "Instituto",
      dataIndex: "institute",
      width: 200,
      editable: true,
      inputType: "text",
    },
    {
      title: "Carrera",
      dataIndex: "career",
      width: 200,
      editable: true,
      inputType: "select",
      options: "career",
    },
    {
      title: "Opción de titulación",
      dataIndex: "titulation_type",
      width: 200,
      editable: true,
      inputType: "text",
    },
    {
      title: "Título de trabajo",
      dataIndex: "project_name",
      width: 200,
      editable: true,
      inputType: "text",
    },
    {
      title: "Asesor interno",
      dataIndex: "int_assessor_name",
      width: 200,
      editable: true,
      inputType: "text",
    },
    {
      title: "Cédula presidente",
      dataIndex: "president_id",
      width: 200,
      editable: true,
      inputType: "select",
      options: "id_card",
    },
    {
      title: "Presidente",
      dataIndex: "president_id",
      width: 200,
      editable: true,
      inputType: "select",
      options: "full_name",
    },
    {
      title: "Profesion presidente",
      dataIndex: "president_id",
      width: 200,
      editable: true,
      inputType: "select",
      options: "profession",
    },
    {
      title: "Cédula secretario",
      dataIndex: "secretary_id",
      width: 200,
      editable: true,
      inputType: "select",
      options: "id_card",
    },
    {
      title: "Secretario",
      dataIndex: "secretary_id",
      width: 200,
      editable: true,
      inputType: "select",
      options: "full_name",
    },
    {
      title: "Profesion secretario",
      dataIndex: "secretary_id",
      width: 200,
      editable: true,
      inputType: "select",
      options: "profession",
    },
    {
      title: "Cédula vocal",
      dataIndex: "vocal_id",
      width: 200,
      editable: true,
      inputType: "select",
      options: "id_card",
    },
    {
      title: "Vocal",
      dataIndex: "vocal_id",
      width: 200,
      editable: true,
      inputType: "select",
      options: "full_name",
    },
    {
      title: "Profesion vocal",
      dataIndex: "vocal_id",
      width: 200,
      editable: true,
      inputType: "select",
      options: "profession",
    },
  ];
};

export default columns;
